export default [
{uid: 1, value: '–', html: '&ndash;', isoCode: '&#8211;', meaning: 'en dash'},
{uid: 2, value: '—', html: '&mdash;', isoCode: '&#8212;', meaning: 'em dash'},
{uid: 3, value: '¡', html: '&iexcl;', isoCode: '&#161;', meaning: 'inverted exclamation'},
{uid: 4, value: '¿', html: '&iquest;', isoCode: '&#191;', meaning: 'inverted question mark'},
{uid: 5, value: '"', html: '&quot;', isoCode: '&#34;', meaning: 'quotation mark'},
{uid: 6, value: '“', html: '&ldquo;', isoCode: '&#8220;', meaning: 'left double curly quote'},
{uid: 7, value: '”', html: '&rdquo;', isoCode: '&#8221;', meaning: 'right double curly quote'},
{uid: 8, value: '\'', html: '&apos;', isoCode: '&#39;', meaning: 'apostrophe (single quote)'},
{uid: 9, value: '‘', html: '&lsquo;', isoCode: '&#8216;', meaning: 'left single curly quote'},
{uid: 10, value: '’', html: '&rsquo;', isoCode: '&#8217;', meaning: 'right single curly quote'},
{uid: 11, value: '«', html: '&laquo;', isoCode: '&#171;', meaning: 'guillemets (used as quotation marks in some languages, e.g., French)'},
{uid: 12, value: '»', html: '&raquo;', isoCode: '&#187;', meaning: ''},
{uid: 13, value: '', html: '&nbsp;', isoCode: '&#160;', meaning: 'non-breaking space'},
{uid: 14, value: '&', html: '&amp;', isoCode: '&#38;', meaning: 'ampersand'},
{uid: 15, value: '¢', html: '&cent;', isoCode: '&#162;', meaning: 'cent'},
{uid: 16, value: '©', html: '&copy;', isoCode: '&#169;', meaning: 'copyright'},
{uid: 17, value: '÷', html: '&divide;', isoCode: '&#247;', meaning: 'divide'},
{uid: 18, value: '>', html: '&gt;', isoCode: '&#62;', meaning: 'greater than'},
{uid: 19, value: '<', html: '&lt;', isoCode: '&#60;', meaning: 'less than'},
{uid: 20, value: 'µ', html: '&micro;', isoCode: '&#181;', meaning: 'micron'},
{uid: 21, value: '·', html: '&middot;', isoCode: '&#183;', meaning: 'middle dot'},
{uid: 22, value: '¶', html: '&para;', isoCode: '&#182;', meaning: 'pilcrow (paragraph sign)'},
{uid: 23, value: '±', html: '&plusmn;', isoCode: '&#177;', meaning: 'plus/minus'},
{uid: 24, value: '€', html: '&euro;', isoCode: '&#8364;', meaning: 'Euro'},
{uid: 25, value: '£', html: '&pound;', isoCode: '&#163;', meaning: 'British Pound Sterling'},
{uid: 26, value: '®', html: '&reg;', isoCode: '&#174;', meaning: 'registered'},
{uid: 27, value: '§', html: '&sect;', isoCode: '&#167;', meaning: 'section'},
{uid: 28, value: '™', html: '&trade;', isoCode: '&#153;', meaning: 'trademark'},
{uid: 29, value: '¥', html: '&yen;', isoCode: '&#165;', meaning: 'Japanese Yen'},
{uid: 30, value: '°', html: '&deg;', isoCode: '&#176;', meaning: 'Degree'},
{uid: 31, value: 'á', html: '&aacute;', isoCode: '&#225;', meaning: 'lower-case "a" with acute accent'},
{uid: 32, value: 'Á', html: '&Aacute;', isoCode: '&#193;', meaning: 'upper-case "A" with acute accent'},
{uid: 33, value: 'à', html: '&agrave;', isoCode: '&#224;', meaning: 'lower-case "a" with grave accent'},
{uid: 34, value: 'À', html: '&Agrave;', isoCode: '&#192;', meaning: 'upper-case "A" with grave accent'},
{uid: 35, value: 'â', html: '&acirc;', isoCode: '&#226;', meaning: 'lower-case "a" with circumflex'},
{uid: 36, value: 'Â', html: '&Acirc;', isoCode: '&#194;', meaning: 'upper-case "A" with circumflex'},
{uid: 37, value: 'å', html: '&aring;', isoCode: '&#229;', meaning: 'lower-case "a" with ring'},
{uid: 38, value: 'Å', html: '&Aring;', isoCode: '&#197;', meaning: 'upper-case "A" with ring'},
{uid: 39, value: 'ã', html: '&atilde;', isoCode: '&#227;', meaning: 'lower-case "a" with tilde'},
{uid: 40, value: 'Ã', html: '&Atilde;', isoCode: '&#195;', meaning: 'upper-case "A" with tilde'},
{uid: 41, value: 'ä', html: '&auml;', isoCode: '&#228;', meaning: 'lower-case "a" with diaeresis/umlaut'},
{uid: 42, value: 'Ä', html: '&Auml;', isoCode: '&#196;', meaning: 'upper-case "A" with diaeresis/umlaut'},
{uid: 43, value: 'æ', html: '&aelig;', isoCode: '&#230;', meaning: 'lower-case "ae" ligature'},
{uid: 44, value: 'Æ', html: '&AElig;', isoCode: '&#198;', meaning: 'upper-case "AE" ligature'},
{uid: 45, value: 'ç', html: '&ccedil;', isoCode: '&#231;', meaning: 'lower-case "c" with cedilla'},
{uid: 46, value: 'Ç', html: '&Ccedil;', isoCode: '&#199;', meaning: 'upper-case "C" with cedilla'},
{uid: 47, value: 'é', html: '&eacute;', isoCode: '&#233;', meaning: 'lower-case "e" with acute accent'},
{uid: 48, value: 'É', html: '&Eacute;', isoCode: '&#201;', meaning: 'upper-case "E" with acute accent'},
{uid: 49, value: 'è', html: '&egrave;', isoCode: '&#232;', meaning: 'lower-case "e" with grave accent'},
{uid: 50, value: 'È', html: '&Egrave;', isoCode: '&#200;', meaning: 'upper-case "E" with grave accent'},
{uid: 51, value: 'ê', html: '&ecirc;', isoCode: '&#234;', meaning: 'lower-case "e" with circumflex'},
{uid: 52, value: 'Ê', html: '&Ecirc;', isoCode: '&#202;', meaning: 'upper-case "E" with circumflex'},
{uid: 53, value: 'ë', html: '&euml;', isoCode: '&#235;', meaning: 'lower-case "e" with diaeresis/umlaut'},
{uid: 54, value: 'Ë', html: '&Euml;', isoCode: '&#203;', meaning: 'upper-case "E" with diaeresis/umlaut'},
{uid: 55, value: 'í', html: '&iacute;', isoCode: '&#237;', meaning: 'lower-case "i" with acute accent'},
{uid: 56, value: 'Í', html: '&Iacute;', isoCode: '&#205;', meaning: 'upper-case "I" with acute accent'},
{uid: 57, value: 'ì', html: '&igrave;', isoCode: '&#236;', meaning: 'lower-case "i" with grave accent'},
{uid: 58, value: 'Ì', html: '&Igrave;', isoCode: '&#204;', meaning: 'upper-case "I" with grave accent'},
{uid: 59, value: 'î', html: '&icirc;', isoCode: '&#238;', meaning: 'lower-case "i" with circumflex'},
{uid: 60, value: 'Î', html: '&Icirc;', isoCode: '&#206;', meaning: 'upper-case "I" with circumflex'},
{uid: 61, value: 'ï', html: '&iuml;', isoCode: '&#239;', meaning: 'lower-case "i" with diaeresis/umlaut'},
{uid: 62, value: 'Ï', html: '&Iuml;', isoCode: '&#207;', meaning: 'upper-case "I" with diaeresis/umlaut'},
{uid: 63, value: 'ñ', html: '&ntilde;', isoCode: '&#241;', meaning: 'lower-case "n" with tilde'},
{uid: 64, value: 'Ñ', html: '&Ntilde;', isoCode: '&#209;', meaning: 'upper-case "N" with tilde'},
{uid: 65, value: 'ó', html: '&oacute;', isoCode: '&#243;', meaning: 'lower-case "o" with acute accent'},
{uid: 66, value: 'Ó', html: '&Oacute;', isoCode: '&#211;', meaning: 'upper-case "O" with acute accent'},
{uid: 67, value: 'ò', html: '&ograve;', isoCode: '&#242;', meaning: 'lower-case "o" with grave accent'},
{uid: 68, value: 'Ò', html: '&Ograve;', isoCode: '&#210;', meaning: 'upper-case "O" with grave accent'},
{uid: 69, value: 'ô', html: '&ocirc;', isoCode: '&#244;', meaning: 'lower-case "o" with circumflex'},
{uid: 70, value: 'Ô', html: '&Ocirc;', isoCode: '&#212;', meaning: 'upper-case "O" with circumflex'},
{uid: 71, value: 'ø', html: '&oslash;', isoCode: '&#248;', meaning: 'lower-case "o" with slash'},
{uid: 72, value: 'Ø', html: '&Oslash;', isoCode: '&#216;', meaning: 'upper-case "O" with slash'},
{uid: 73, value: 'õ', html: '&otilde;', isoCode: '&#245;', meaning: 'lower-case "o" with tilde'},
{uid: 74, value: 'Õ', html: '&Otilde;', isoCode: '&#213;', meaning: 'upper-case "O" with tilde'},
{uid: 75, value: 'ö', html: '&ouml;', isoCode: '&#246;', meaning: 'lower-case "o" with diaeresis/umlaut'},
{uid: 76, value: 'Ö', html: '&Ouml;', isoCode: '&#214;', meaning: 'upper-case "O" with diaeresis/umlaut'},
{uid: 77, value: 'ß', html: '&szlig;', isoCode: '&#223;', meaning: 'ess-tsett'},
{uid: 78, value: 'ú', html: '&uacute;', isoCode: '&#250;', meaning: 'lower-case "u" with acute accent'},
{uid: 79, value: 'Ú', html: '&Uacute;', isoCode: '&#218;', meaning: 'upper-case "U" with acute accent'},
{uid: 80, value: 'ù', html: '&ugrave;', isoCode: '&#249;', meaning: 'lower-case "u" with grave accent'},
{uid: 81, value: 'Ù', html: '&Ugrave;', isoCode: '&#217;', meaning: 'upper-case "U" with grave accent'},
{uid: 82, value: 'û', html: '&ucirc;', isoCode: '&#251;', meaning: 'lower-case "u" with circumflex'},
{uid: 83, value: 'Û', html: '&Ucirc;', isoCode: '&#219;', meaning: 'upper-case "U" with circumflex'},
{uid: 84, value: 'ü', html: '&uuml;', isoCode: '&#252;', meaning: 'lower-case "u" with diaeresis/umlaut'},
{uid: 85, value: 'Ü', html: '&Uuml;', isoCode: '&#220;', meaning: 'upper-case "U" with diaeresis/umlaut'},
{uid: 86, value: 'ÿ', html: '&yuml;', isoCode: '&#255;', meaning: 'lower-case "y" with diaeresis/umlaut'},
{uid: 87, value: '´', html: '', isoCode: '&#180;', meaning: 'acute accent with no letter'},
{uid: 88, value: '`', html: '', isoCode: '&#96;', meaning: 'grave accent/reversed apostrophe with no letter'}
];
